CLASS zcl_bs_bc26_factory DEFINITION
  PUBLIC ABSTRACT FINAL
  CREATE PRIVATE.

  PUBLIC SECTION.
    CLASS-METHODS create
      RETURNING VALUE(result) TYPE REF TO zif_bs_bc26_interface.
ENDCLASS.


CLASS zcl_bs_bc26_factory IMPLEMENTATION.
  METHOD create.
    RETURN NEW zcl_bs_bc26_private( ).
  ENDMETHOD.
ENDCLASS.
